(define-module (modules zsh)
  #:use-module (gnu home)
  #:use-module (gnu services)
  #:use-module (gnu services guix)
  #:use-module (gnu home services shells)
  #:use-module (gnu home services guix))

(define-public zsh-service
  (service home-zsh-service-type
           (home-zsh-configuration
            (zshenv
             (list "GUIX_PROFILE=\"${HOME}/.config/guix/current\""
                   ". \"$GUIX_PROFILE/etc/profile\""
                   "GUIX_PROFILE=\"${HOME}/.guix-home/profile\""
                   ". \"${HOME}/.guix-home/profile/etc/profile\""
                   "export GUIX_LOCPATH=\"${HOME}/.guix-profile/lib/locale\""))
            ; (zlogin
            ;  (list "# gnu guix"
            ;        "GUIX_LOCPATH=\"$HOME/.guix-profile/lib/locale\""
            ;        "GUIX_PROFILE=\"/home/nomike/.config/guix/current\""
            ;        "PATH=\"${HOME}/.guix-home/profile/bin:/home/nomike/.local/bin:/home/nomike/go/bin:${PATH}\""
            ;        "# make less more friendly for non-text input files, see lesspipe(1)"
            ;        "[ -x /usr/bin/lesspipe ] && eval \"$(SHELL=/bin/sh lesspipe)\""))
            (zshrc
             (list "#eval $(thefuck --alias) # Disabled as it's incompatible with python 3.12"
                   ""
                   "source /usr/share/zsh-antigen/antigen.zsh"
                   ""
                   "antigen use oh-my-zsh"
                   "antigen bundle git"
                   "antigen bundle dircycle"
                   "antigen bundle command-not-found"
                   "antigen bundle common-aliases"
                   "antigen bundle thefuck"
                   "antigen bundle zsh-users/zsh-syntax-highlighting"
                   "antigen bundle zsh-users/zsh-autosuggestions"
                   "antigen theme nomike/agnosterzak-ohmyzsh-theme agnosterzak"
                   "antigen apply"
                   ""
                   "export MOZ_ENABLE_WAYLAND=1"
                   ""
                   "alias yt10=\"yt-dlp -N 10\""
                   "alias gpl3='wget https://www.gnu.org/licenses/gpl-3.0.txt -O LICENSE'"
                   "alias cc0='wget https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt -O LICENSE'"
                   ""
                   "function mit() {"
                   "\techo \"MIT License\\n\\"
                   "\\n\\"
                   "Copyright (c) $( date +%Y ) nomike[AT]nomike[DOT]com\\n\\"
                   "\\n\\"
                   "Permission is hereby granted, free of charge, to any person obtaining a copy\\n\\"
                   "of this software and associated documentation files (the \"Software\"), to deal\\n\\"
                   "in the Software without restriction, including without limitation the rights\\n\\"
                   "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\\n\\"
                   "copies of the Software, and to permit persons to whom the Software is\\n\\"
                   "furnished to do so, subject to the following conditions:\\n\\"
                   "\\n\\"
                   "The above copyright notice and this permission notice shall be included in all\\n\\"
                   "copies or substantial portions of the Software.\\n\\"
                   "\\n\\"
                   "THE SOFTWARE IS PROVIDED \\\"AS IS\\\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\\n\\"
                   "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\\n\\"
                   "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\\n\\"
                   "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\\n\\"
                   "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\\n\\"
                   "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\\n\\"
                   "SOFTWARE.\\n\" >LICENSE"
                   "}"
                   ""
                   "function bsd2() {"
                   "  echo \"Copyright $( date +%Y ) nomike[AT]nomike[DOT]com\\n\\"
                   "\\n\\"
                   "Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:\\n\\"
                   "\\n\\"
                   "1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.\\n\\"
                   "\\n\\"
                   "2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.\\n\\"
                   "\\n\\"
                   "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \\\"AS IS\\\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\\n\" >LICENSE"
                   "}"
                   ""
                   "function 3ddinit() {"
                   "\tif [[ -d .git ]] ; then"
                   "\t\techo \"This is already a git repository. Aborting...\""
                   "\t\treturn 1"
                   "\tfi"
                   ""
                   "\tgit init"
                   "\tcp -r ~/3ddesignskel/* ~/3ddesignskel/.* ."
                   "\tgit add ."
                   "\tgit commit -m \"Import 3D-Design skeleton\""
                   "\tgit submodule add -- https://github.com/nomike/openscad_stl_file_generator"
                   "\t("
                   "\t\tcd openscad_stl_file_generator"
                   "\t\tgit fetch --tags"
                   "\t\tgit checkout \"$(git describe --tags \"$(git rev-list --tags --max-count=1)\")\""
                   "\t)"
                   "\tgit add ."
                   "\tgit commit -m \"Add openscad_stl_file_generator submodule\""
                   "}"
                   ""
                   "#Virtualenvwrapper settings:"
                   "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3"
                   "export WORKON_HOME=$HOME/.virtualenvs"
                   "export VIRTUALENVWRAPPER_VIRTUALENV=virtualenv"
                   "source /usr/share/virtualenvwrapper/virtualenvwrapper.sh"
                   ""
                   "autoload -Uz compinit"
                   "zstyle ':completion:*' menu select"
                   "fpath+=~/.zfunc"
                   ""
                   "# Report execution time for commands running 30 seconds or longer"
                   "export REPORTTIME=30"
                   ""
                   "GUIX_PROFILE=\"/home/nomike/.config/guix/current\""
                   ". \"$GUIX_PROFILE/etc/profile\""
                   "GUIX_PROFILE=\"/home/nomike/.guix-home/profile\""
                   ". \"${HOME}/.guix-home/profile/etc/profile\""
                   ""
                   "function lx3000volumefix() {"
                   "\tfor device in $( aplay -l | grep \"Microsoft LifeChat LX-3000\" | cut -d ' ' -f 2 | tr -d ':' ) ; do"
                   "\t\tamixer set 'Speaker' 100% -c \"${device}\" >/dev/null;"
                   "\tdone"
                   "}"
                   ""
                   "export GUIX_LOCPATH=\"$HOME/.guix-profile/lib/locale\""
                   ""
                   "# codeberg-cli"
                   "eval $( berg completion zsh)"
                   ""
                   "export ENVTEST_ZSHRC=\"noguixmike\""
                   ""
                   "# Add Claude Code to PATH"
                   "export PATH=\"$HOME/.claude/local:$PATH\"")))))